### ISSUE TITLE
The application uses the Date object in react without noting timezone.

### ISSUE THREAD

**Issue by dannychuy** [csmberkeley/website#3]
https://github.com/csmberkeley/website/blob/master/src/pages/Mentors.tsx

The problem with this is that React uses the the local machine's timezone and date/time. Since it converts the json's time into the respective timezone, the deadline will appear in different times and I feel like that would be confusing.

Easiest fix I can think about is just adding what timezone the deadline is listed as.

**Comment by noloerino** [comment]
fixed in 61326b, the deadline is now always displayed in Pacific time
