### ISSUE TITLE
Change the expectations doc

### ISSUE THREAD

**Issue by dannychuy** [csmberkeley/website#4]
The documents fo the expectations are found in the Structural Doc Shared Folder. Can someone change the links to them?
https://csmentors.berkeley.edu/#/students
- https://docs.google.com/document/d/1fmzgepezzdEzfi97u_jEw3OS88gsKDh7AjpuB4pnuLA/edit?usp=sharing

etc for JM/SM/Exec.... https://drive.google.com/drive/u/0/folders/0AHFvLKiJAqKeUk9PVA

**Comment by noloerino** [comment]
Seems like the JM/AM/SM/Exec expectations are all unshared.

**Comment by dannychuy** [comment]
JM: https://docs.google.com/document/d/1BydWEl-BMCxYuy2u7W5ObFhe-n4Kb41BzsBknH0BkbA/edit?usp=sharing
SM: https://docs.google.com/document/d/16fsK37U0wiXmW_9J-qM6MhCczcxL11ObGYCU7qnlHM0/edit?usp=sharing
AM: https://docs.google.com/document/d/1agPwxUWVr_3J1Nb-PhkvOc9254xywKrhb13p1Cpfh_M/edit?usp=sharing
Exec: We can wait later.

**Comment by noloerino** [comment]
Updated in https://github.com/csmberkeley/website/commit/3b437ea986cb8ffdcdb2d43c535cca90feb83388
